metadata:
  name: bs-${project.artifactId}
data:
  application.properties: |
    logging.level.qslv=DEBUG
    qslv.enhanced-request-topic=qks.enhanced.request
    qslv.posting-response-topic=qks.posting.response
    qslv.posting-request-topic=qks.posting.request
    qslv.account-log-topic=qks.account
    qslv.overdraft-log-topic=qks.overdraft.instructions
    qslv.match-reservation-topic=qks.match.reservation
    qslv.kafka-consumer-properties-path=/deployments/config/kafka-consumer/kafka.properties
    qslv.kafka-producer-properties-path=/deployments/config/kafka-producer/kafka.properties
    qslv.kafka-streams-properties-path=/deployments/config/kafka-streams/kafka.properties
    management.endpoint.health.show-details=always
    management.endpoint.health.show-components=always
    